image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - usernamehw.errorlens
    - vscode-icons-team.vscode-icons
    - bierner.markdown-preview-github-styles
    - ms-python.python
    - KevinRose.vsc-python-inden